### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by aschuch** [leecrossley/cordova-plugin-apple-watch#10]
- attribute [MMWormhole](https://github.com/mutualmobile/MMWormhole) in the Readme
- add MMWormhole License to this project
- update the Readme with an example on how to use MMWormhole in the native WatchKit extension

**Comment by leecrossley** [comment]
There are now also [message passing examples](https://github.com/leecrossley/cordova-plugin-apple-watch#message-passing-examples) in the readme.
