### ISSUE TITLE
Working principles plugin

### ISSUE THREAD

**Issue by ghost** [leecrossley/cordova-plugin-apple-watch#13]
Hello, I'm writing because I don't understand this plugin very well. I understood the working principles because I read the official documentation (https://developer.apple.com/library/ios/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969-CH8-SW1). Reading the plugin I don't understand how I can custom my interface on my apple watch, I don't undestrand how my iphone and my watch communicate. Moreover the method init intall my storyboard on apple watch? Thank you!

**Comment by leecrossley** [comment]
You will need to write your own WatchKit Extension and WatchKit app with native code, this plugin only provides various methods of communication to and from your Cordova app.

The readme has been updated with more information to help you understand the different types of communication. There are now also [message passing examples](https://github.com/leecrossley/cordova-plugin-apple-watch#message-passing-examples) to get you started.
