### ISSUE TITLE
 Implement application:handleWatchKitExtensionRequest:reply:

### ISSUE THREAD

**Issue by jbeuckm** [leecrossley/cordova-plugin-apple-watch#15]
This seems like a pretty common use case, after starting to work with Apple Watch a bit.

**Comment by leecrossley** [comment]
Shouldn't this be implemented in your Apple Watch App and subsequently WatckKit extension? What is it you're trying to achieve and I'll try to help but I don't think it relates to this plugin.

**Comment by leecrossley** [comment]
OK, closing for now, feel free to reopen if required
