### ISSUE TITLE
Unable to sendNotification - NSInvalidArgumentException

### ISSUE THREAD

**Issue by etiennea** [leecrossley/cordova-plugin-apple-watch#17]
applewatch.sendNotification(function(e) { console.log('WatchOK')

returns is the successHandler but then crashes every time, both my success and error function are just function(e){console.log(e)} and my variables are the default example ones.

2015-06-28 18:39:42.060 Recipes[1684:287989] WatchOK
2015-06-28 18:39:42.074 Recipes[1684:287989] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'
**\* First throw call stack:
(0x1844642d8 0x195c880e4 0x184464218 0x1853d8ee4 0x1000b0238 0x1000ac7c4 0x1000abf90 0x18440a2c4 0x184347450 0x185276a80 0x1000689d4 0x189139224 0x18912fbf0 0x18cc6d3c8 0x18441c27c 0x18441b384 0x1844199a8 0x1843452d4 0x18db5b6fc 0x188f0afac 0x100068304 0x196306a08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by leecrossley** [comment]
Can I please see the rest of the arguments you are passing to the `sendNotification` function. I assume you have called `registerNotifications` and received a success callback before attempting to send a notification?

**Comment by leecrossley** [comment]
It does sound like you are not following the payload schema

``` js
var payload = {
    "title": "Short!",
    "category": "default",
    "body": "Shown in the long-look interface to provide more detail",
    "badge": 1
};
```

**Comment by etiennea** [comment]
My payload is the same as yours

```
var payload = {
    "title": "Short!",
    "category": "default",
    "body": "Shown in the long-look interface to provide more detail",
    "badge": 1
  };

  if (window.appleWatchOk)
    applewatch.sendNotification(function(e) {
      console.log('WatchOK')
    }, function(e) {
      console.log('WatchErr')
    }, payload);
```

And then before that in my onDeviceReady function

```
if (!window.appleWatchStarted) {
window.appleWatchStarted = true;
applewatch.init(function(appGroupId) {
    console.log('appleWatch', appGroupId)
    // success, messages may now be sent or listened for
    applewatch.registerNotifications(function(e) {
      window.appleWatchOk = true;
      console.log('appleWatch', e)
    }, function(e) {
      console.log('appleWatchErr', e)
    });
  }, function(err) {
    console.log('appleWatchErr', err)
    // an error occurred
  },
  "com.etiennea.watch");
```

  }

**Comment by leecrossley** [comment]
You are mixing up 2 methodologies, you're calling the `init` function for [message passing](https://github.com/leecrossley/cordova-plugin-apple-watch#message-passing) and then attempting to call `sendNotification` for [notifications](https://github.com/leecrossley/cordova-plugin-apple-watch#notifications).
- If you want to send notifications with `sendNotification`, you need to register for notifications first with `registerNotifications`
- If you want to send messages with `sendMessage`, you need to initialise the Apple Watch two way messaging interface first with `init`

Here are the [methods of communication](https://github.com/leecrossley/cordova-plugin-apple-watch#supported-methods-of-communication) that work independently of each other.

Please read all the docs in detail and decide on your objectives and approach before raising any more issues. Github issues are generally for issues with the plugin, not technical programming assistance.

Good luck!

**Comment by etiennea** [comment]
Sorry! I totally understand that. I have read the docs.  

I am calling registerNotifications, just nested in the other one because I was intending to do both. They both succeed, init and register. 

The send method also succeeds. In fact the notification appears on my phone. It fails straight after. 

Thank you for your help and time, I think it is useful to have this conversation here as I may not be the only one struggling with this issue. Could it be a conflict with the local notification plugin?

**Comment by leecrossley** [comment]
As yes, sorry I missed the nested call skim reading.

It could absolutely be a conflict with a local notification plugin, do you need the 2 to run alongside each other? If there's a missing feature you need in the watch plugin, it makes sense to implement it here.

**Comment by etiennea** [comment]
Yes I cannot remove local notifications, my app relies extensively on that plugins scheduling capabilities amongst other things, plus it plays sounds and works on android. I will remove it just to see if that was the issue and let you know.

**Comment by leecrossley** [comment]
Ok, I suggest using the local notifications plugin you're already using for notifications and only use this plugin for message passing etc.

**Comment by etiennea** [comment]
Yes, so there is indeed a conflict as it works without the other plugin. 

That is what I was thinking I just need to figure out how to add the "body" and "category" params to the localnotifications plugin.

In any case thank you for being so helpful and on a sunday!

**Comment by leecrossley** [comment]
Makes sense, [this is the code](https://github.com/leecrossley/cordova-plugin-apple-watch/blob/master/src/ios/AppleWatch.m#L76-L84) that needs to be incorporated into the other plugin (along with the js interface). Hope this helps and once again good luck!
