### ISSUE TITLE
Plugin not accessable!

### ISSUE THREAD

**Issue by nerdsupremacist** [leecrossley/cordova-plugin-apple-watch#18]
I've seen this problem here before, and it seems like it hasn't been solved.
Whenever I try to access applewatch it's undefined. I can't access it. Now before you tell me to reinstall the plugin or recreate the platform, it's already been done twice. Is there anything I might be forgetting, when calling the plugin. Perhaps I have to include it into the controller? or app.js?

**Comment by leecrossley** [comment]
`applewatch` is available as a global variable on the root scope when the plugin is installed correctly. What version of Cordova are you using?

**Comment by nerdsupremacist** [comment]
I'm running cordova 5.1.1. But if it's on the rootScope perhaps it should be in $rootScope.applewatch instead of applewatch? I'm sorry. I'm pretty new to cordova. I've always programmed in obj-c or swift but the client wants something using ionic.

**Comment by nerdsupremacist** [comment]
Nevermind. I'm closing this. I forgot to only call it when the device is ready. lol! Sorry:)
