### ISSUE TITLE
Native code to handle calls from the watch without using an additional cordova plugin

### ISSUE THREAD

**Issue by devnill** [leecrossley/cordova-plugin-apple-watch#21]
I'm using this plugin to run a native watch app that asks cordova to make network requests via AJAX. The issue I'm facing is that this means that requests won't fire if the app itself is not in the foreground.

I'd like to create a native component on the phone that can be woken up by the watch app that can make requests on behalf of the watch. It looks like that `WKInterfaceController.openParentApplication` is able to do this, but I'm not sure how to integrate this on the phone side.

I'm not sure if this is the correct place to ask, but I thing it would be a great feature considering a network connected watch app isn't very useful if the phone screen needs to be on constantly.

**Comment by webbpage** [comment]
This is a helpful comment for someone looking into this cordova plugin. Has this been resolved? Also, are there plans to submit this plugin to PhoneGap Build?

**Comment by leecrossley** [comment]
I'm afraid to say @devnill that `openParentApplication` will not open your iOS app.

Personally, I'd implement the network requests in your WatchKit Extension and you shouldn't have any problems.

p.s. @webbpage this plugin is currently not suited to PhoneGap Build, as it requires native code
