### ISSUE TITLE
Use of unresolved identifier MMWormhole

### ISSUE THREAD

**Issue by msrameshp** [leecrossley/cordova-plugin-apple-watch#22]
Hi Leecrossley,

I am having an issue "Use of unresolved identifier MMWormhole" when I am trying to run the following code in the watch kit Extension InterfaceController ;

let wormhole = MMWormhole(applicationGroupIdentifier: "group.dtz.au", optionalDirectory: nil);

Is this because the iWatch code is in swift and the library is in Objective-c ?. do I need like a bridging header to resolve this ?.

Please advice.

**Comment by leecrossley** [comment]
Please see the answer [here](https://github.com/leecrossley/cordova-plugin-apple-watch/issues/16#issuecomment-126084296)
