### ISSUE TITLE
Making sure I understand purpose :)

### ISSUE THREAD

**Issue by dgerding** [leecrossley/cordova-plugin-apple-watch#24]
Hi Lee,
Thanks for all the effort on this.  We have a prototype apple watch app that runs, builds and deploys to real watches.  What we're wondering is can we use this plugin to get our Cordova app to trigger events/handlers in the Watch app?  I'm assuming that would mean bundling the iOS watch ipa and the watch app in some way as a resource inside the Cordova app ios resources?  

Am I on the right track here?  And is there any demo code or documentation about communication from the phonegap app to the iOS watch app?

Thanks,
Dave

**Comment by leecrossley** [comment]
Hi Dave, you want to look at the [message passing](https://github.com/leecrossley/cordova-plugin-apple-watch#message-passing) section. You'd then simply install this plugin with your cordova app and include the mmwormhole lib in your WatchKit Extension. There are examples on the readme if you get stuck.

**Comment by dgerding** [comment]
Thanks!  I guess I have a different question, too.  Once we've got IPAs for the watch app and extension pair (always get that naming mixed up) is there a way and/or what is the best way to include the IPAs in the Cordova iOS resources (presumably) so that when the Cordova app is installed, the apple watch functionality is installed, too?
