### ISSUE TITLE
Should this plugin work with WatchOS 2 and iOS 9?

### ISSUE THREAD

**Issue by tuomaslahti** [leecrossley/cordova-plugin-apple-watch#27]
Hi,

i'm having trouble using this plugin with watchOS 2 and iOS 9, both running on simulator.

I've configured app groups correctly (I think) and my project compiles without errors, but I just can't send or receive messages on either device.

MMWormhole has recently added MMWormholeSession and WatchConnectivity Support in https://github.com/mutualmobile/MMWormhole/pull/50

Maybe this plugin needs those updates as well?

**Comment by Mojo90** [comment]
I updated this by myself in AppleWatch.m to work together with new MMWormhole and does work for me. I can send a Pull Request later to let you know.

**Comment by EddyVerbruggen** [comment]
@Mojo90 I would be very interested, so please do :)

**Comment by Mojo90** [comment]
Please see this pull request: #28
