### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by ElBrad** [leecrossley/cordova-plugin-apple-watch#29]
I tried installing the plugin, then opening the xproj, adding a new watchos target and building.

**When building through simulator**
The app builds successfully, the watch simulator shows a black screen (haven't added anything to the storyboard yet)

**When building to device**
I get the following error:

ld: framework not found AVFoundation
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried linking the framework to the apple watch and the extension, no joy, tried removing the dependencies from the watch app, no luck.

Please advise?

**Comment by leecrossley** [comment]
Please use the latest version of the plugin (v0.11.0) which includes updates for MMWormhole and watchOS 2.

**Comment by bojanvidanovic** [comment]
Using 0.11.3 and i get the same issue.

**Comment by shaikhtariq11** [comment]
Same error. +1
