### ISSUE TITLE
need full example

### ISSUE THREAD

**Issue by mohamedzaher88** [leecrossley/cordova-plugin-apple-watch#3]
how can i use this plugin , any body can help me need full example
thanks

**Comment by leecrossley** [comment]
I'm planning a blog post later this month to explain this in detail with code samples and possibly a demo watch app along side it.

In the meantime, I suggest you look at the [usage](https://github.com/leecrossley/cordova-plugin-apple-watch#usage) on the README and the following resources on how to implement your watch app:
- [Apple WatchKit](https://developer.apple.com/watchkit/)
- [WatchKit Programming Guide](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/WatchKitProgrammingGuide/)

If you have specific questions or bugs, please raise another issue.
