### ISSUE TITLE
cordova build ios FAILED on watchos2

### ISSUE THREAD

**Issue by beatgrabe** [leecrossley/cordova-plugin-apple-watch#34]
Someone else facing this problem on `cordova build ios` with this plugin?

```
Check dependencies
target specifies product type 'com.apple.product-type.watchkit2-extension',
but there's no such product type for the 'iphonesimulator' platform

** BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig, */platforms/ios/cordova/build-
debug.xcconfig,-project,*.xcodeproj,ARCHS=i386,-target,*,-configuration,Debug,-
sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=*/platforms/ios/build
/emulator,SHARED_PRECOMPS_DIR=*/platforms/ios/build/sharedpch
```

I have already found this [issue](https://forums.developer.apple.com/thread/5435) in the apple dev forum, tried solutions, but nothing helped. I am considering that the error is cordova related, and i just have to continue using xcode building until there is a cordova platform update?!

**Comment by leecrossley** [comment]
You should use Xcode if you use this plugin, it's not something this plugin can resolve unfortunately.

**Comment by beatgrabe** [comment]
Ok thanks.
I have already fed up with this issue by ignoring it and building with xcode!
