### ISSUE TITLE
WatchConnectivity/WatchConnectivity.h file not found

### ISSUE THREAD

**Issue by zw11223344** [leecrossley/cordova-plugin-apple-watch#35]
When build cordova app ,plugins/cordova-plugin-apple-watch/MMWormholeSession.h:26:9: fatal error: 'WatchConnectivity/WatchConnectivity.h' file not found.

**Comment by leecrossley** [comment]
Please ensure you have the latest version of Xcode and have the WatchConnectivity.framework, the plugin will [automatically add this](https://github.com/leecrossley/cordova-plugin-apple-watch/blob/10b5a2c76c027ed23c6b6e65f9d720ff81bf44b7/plugin.xml#L42) on plugin install (`cordova plugin add cordova-plugin-apple-watch`).
