### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by shaikhtariq11** [leecrossley/cordova-plugin-apple-watch#37]
After project setup while building project "ProjectNameWatch Extension" target shows below error:

ld: file not found: path.../Build/Products/Debug-watchsimulator/libCordova.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please let me know if i am missing anything? 
Using :
0.11.3 plugin version
XCODE 7.1.1
Latest Cordova 5.4.1
cordova ios 3.9.2
watchOS 2
swift

**Comment by JanMisker** [comment]
I had the same issue but figured out that I had 
`-force_load "$(BUILT_PRODUCTS_DIR)/libCordova.a"`
in "Other Links Flags", removing that solved this issue for me.
