### ISSUE TITLE
No communication

### ISSUE THREAD

**Issue by patronovski2** [leecrossley/cordova-plugin-apple-watch#38]
The phone app and the watch app can't communicate.
GroupId added, plugin initializes succesfully, MMWormhole added via Cocoapods. 

XCode 7.1
WatchOS 2
iOS 9

**Comment by NorthMcCormick** [comment]
I've been trying for a while, I can't seem to get it to work either. :( No errors though

**Comment by patronovski2** [comment]
I also get no errors. Very strange. Is there something that i have to enable in Xcode besides the groupId?

**Comment by mouryaamit** [comment]
@patronovski2 @NorthMcCormick did you got any working solution

**Comment by patronovski2** [comment]
Still no solution here. Can anybody please post an example for apple watch os2

**Comment by partclay** [comment]
I got it to work, see how here: [https://github.com/leecrossley/cordova-plugin-apple-watch/issues/39](https://github.com/leecrossley/cordova-plugin-apple-watch/issues/39)
