### ISSUE TITLE
no comunication...Watch OS2

### ISSUE THREAD

**Issue by taehoo** [leecrossley/cordova-plugin-apple-watch#39]
Do App Groups still work on Watch OS 2 as a mechanism for sharing files between the watch and iPhone?

I read the documentation on Watch Connectivity framework. 

App Groups are no longer applicable

"cordova-plugin-apple-watch" support watch os2??
.

**Comment by taehoo** [comment]
I solved this Issue. I used Watch OS2  -> watch kit extention

 MMWormholeSession *session = [MMWormholeSession sharedListeningSession];
 [session activateSessionListening];
 [session listenForMessageWithIdentifier:@"myqueue" listener:^(id  _Nullable messageObject) {
      //Linsten Message  
  }]; ----> O

Instead of

[[MMWormhole alloc] initWithApplicationGroupIdentifier:@"group.com.xxx.xxx" optionalDirectory:nil];   --->  X

**Comment by patronovski2** [comment]
I also have no communication. The plugin initializes correctly, no errors at all. I also added the group id.

**Comment by partclay** [comment]
I struggled with it but finally got it to work. Here are the pitfalls I had to find my way arround.

A. App Groups - there is lots of documentation on how to set this up for MMWormhole. See the troubleshooting section here: [https://github.com/mutualmobile/MMWormhole](https://github.com/mutualmobile/MMWormhole)

B. "queueName" and "identifier" should be the same value (my code below sets both to "messageIdentifier"). For example if you send a notification from Swift with:
`wormhole.passMessageObject("titleString", identifier: "messageIdentifier")`
You should listen for the message in your cordova App with:

```
applewatch.addListener("messageIdentifier", function (message) {
// handle your message here
});
```

The message passing examples here [https://github.com/leecrossley/cordova-plugin-apple-watch](https://github.com/leecrossley/cordova-plugin-apple-watch) show have different "queueName" and "identifier" values which stopped it working for me... until I read through the Obj-C source for the plugin and figured this out.

C. The following initialization code alone won't work:
`let wormhole = MMWormhole(applicationGroupIdentifier: "group.com.yourcompany", optionalDirectory: nil)`
Behind the scenes the Apple Watch Cordova plugin initializes MMWormhole using MMWormholeSession, but the default initialization of MMWormhole as shown in the sample and above doesn't use MMWormholeSession. They both need to use it to pass messages. 
To initialize MMWormholeSession from your watch app do something like this instead:

```
let watchConnectivityListeningWormhole = MMWormholeSession.sharedListeningSession();
watchConnectivityListeningWormhole.activateSessionListening();
let wormhole = MMWormhole(applicationGroupIdentifier: "group.com.yourcompany", optionalDirectory: nil, transitingType: .SessionContext);
```

**Comment by leecrossley** [comment]
@partclay - thanks very much for taking the time to document this in detail. Would you like to pull request the readme with corrected / additional information?
