### ISSUE TITLE
Queue name?

### ISSUE THREAD

**Issue by sean-hill** [leecrossley/cordova-plugin-apple-watch#4]
Hey I'm curious what the `queueName` is in the follow code:

```
applewatch.sendMessage(message, queueName, successHandler, errorHandler);
```

Thanks!

**Comment by leecrossley** [comment]
`queueName` can be any "string" that distinguishes your type of message. You can have a different queueName for different types of messages that you want to handle differently. A listener handles a specific queue and only listens for messages with that queueName.
