### ISSUE TITLE
Works when building and running on simulator ... but gives error when using devices

### ISSUE THREAD

**Issue by RichardBoyder** [leecrossley/cordova-plugin-apple-watch#44]
I get this error when trying to build for iphone 6 and apple watch connected.

Ld /Users/richardboyder/Library/Developer/Xcode/DerivedData/IQMedicalAidApp-cevivvqawazxthdkkxcdkhlearts/Build/Products/Debug-watchos/IQmedicalAidAppWatchkit\ Extension.appex/IQmedicalAidAppWatchkit\ Extension normal armv7k
    cd /Users/richardboyder/Documents/workspace/IQMedicalAidApp_IOS/app/app/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export WATCHOS_DEPLOYMENT_TARGET=2.1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7k -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.1.sdk -L/Users/richardboyder/Library/Developer/Xcode/DerivedData/IQMedicalAidApp-cevivvqawazxthdkkxcdkhlearts/Build/Products/Debug-watchos -F/Users/richardboyder/Library/Developer/Xcode/DerivedData/IQMedicalAidApp-cevivvqawazxthdkkxcdkhlearts/Build/Products/Debug-watchos -filelist /Users/richardboyder/Library/Developer/Xcode/DerivedData/IQMedicalAidApp-cevivvqawazxthdkkxcdkhlearts/Build/Intermediates/IQMedicalAidApp.build/Debug-watchos/IQmedicalAidAppWatchkit\ Extension.build/Objects-normal/armv7k/IQmedicalAidAppWatchkit\ Extension.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -mwatchos-version-min=2.1 -dead_strip -fembed-bitcode-marker -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -framework WatchKit -fobjc-arc -fobjc-link-runtime -fapplication-extension -Xlinker -dependency_info -Xlinker /Users/richardboyder/Library/Developer/Xcode/DerivedData/IQMedicalAidApp-cevivvqawazxthdkkxcdkhlearts/Build/Intermediates/IQMedicalAidApp.build/Debug-watchos/IQmedicalAidAppWatchkit\ Extension.build/Objects-normal/armv7k/IQmedicalAidAppWatchkit\ Extension_dependency_info.dat -o /Users/richardboyder/Library/Developer/Xcode/DerivedData/IQMedicalAidApp-cevivvqawazxthdkkxcdkhlearts/Build/Products/Debug-watchos/IQmedicalAidAppWatchkit\ Extension.appex/IQmedicalAidAppWatchkit\ Extension

ld: framework not found AVFoundation
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you know what is causing this?

**Comment by mouryaamit** [comment]
@RichardBoyder can you please provide the sample codebase/steps how you had integrated

**Comment by RichardBoyder** [comment]
I had to remove my changes so i don't have my working files any more.
but i followed this to the word:
it comes from a Telerik build but uses your plugin.

Installation

Prep
Install npm 'xcode' package because our hooks need it: npm install -g xcode
CLI
 cordova create applewatchtest
 cd applewatchtest
 cordova platform add ios

XCode
File > New > Target > Apple Watch: Language ObjC, Select Glance and Notifications > Finish > Activate
CLI
 cordova plugin add https://github.com/Telerik-Verified-Plugins/AppleWatch
 cordova prepare

XCode
Set CFBundleVersion (Bundle Version) and CFBundleShortVersionString (Bundle versions string, short) of all targets to the same value (use XCode's search feature and change all 3 .plist values)At this point your builds should succeed
More XCode
App Groups: register an appgroup in your iOS member center (Identifiers > App Groups): we expect group., like group.io.cordova.hellocordova, then add it to your App ID. Now generate a provisioning profile with the new App ID and add it XCode (download, then double-click the file should do it). In XCode, go to your targets and add this app group to both the phone and watch app targets (Capabilities tab).
Tips:
Building in XCode 7 requires you to set bitcode to NO for all 3 targets. Go to 'Build Settings' and disable it 3 times. Will be fixed soon, when MMWormhole is updated. 
I pretty much did everything, and my apple watch was connected and as i say, when i ran on simulator it didn't give the error i received but for some reason wouldn't build to the device.
Have you got it working , or perhaps have a sample project created that i could try in my environment to run ? 

---

Richard Boyder
Skype: richarddeerflame@yahoo.com

```
  From: Amit Mourya <notifications@github.com>
```

 To: leecrossley/cordova-plugin-apple-watch cordova-plugin-apple-watch@noreply.github.com 
Cc: RichardBoyder richarddeerflame@yahoo.com
 Sent: Sunday, February 14, 2016 2:56 PM
 Subject: Re: [cordova-plugin-apple-watch] Works when building and running on simulator ... but gives error when using devices (#44)

@RichardBoyder can you please provide the sample codebase/steps how you had integrated—

**Comment by leecrossley** [comment]
Looks like you're using a Telerik plugin, not this one.
