### ISSUE TITLE
Where did you place the initialise message

### ISSUE THREAD

**Issue by LeoLR** [leecrossley/cordova-plugin-apple-watch#46]
Hi, 

I'm trying to use your plugin, but i dond't know how to place this in the cordova application? 

`applewatch.init(function (appGroupId) {
    // success, messages may now be sent or listened for
}, function (err) {
    // an error occurred
},
"group.com.yourcompany");
`

And where did you place the "Initialise message passing (WatchKit extension, swift)":

`let wormhole = MMWormhole(applicationGroupIdentifier: "group.com.yourcompany", optionalDirectory: nil)`

Thank you :disappointed:

**Comment by LeoLR** [comment]
@leecrossley can you help me? :disappointed:

**Comment by leecrossley** [comment]
This is needs to be written in swift, unfortunately this plugin requires some knowledge of native code development on iOS
