### ISSUE TITLE
How to include MMWormhole in swift (New)

### ISSUE THREAD

**Issue by jingkecn** [leecrossley/cordova-plugin-apple-watch#49]
Anyone managed to include MMWormhole in Swift now?
I followed the steps suggested in the previous issue #16 but as mentioned before there's no libmmwormhole.a file found.
Any suggestions please?

**Comment by jingkecn** [comment]
Problem solved:
as marked at #41 by @partclay, select each MMWormhole*.m file in the "Plugins" directory within your Xcode project, then in the file inspector check the target membership for the files to include your watch extension build target. If your watch extension is written in Swift you will also need to update your Bridging-Header.h in the "Other Sources" folder to import the MMWormhole.h file, eg:
#import "MMWormhole.h" and remove #import Cordova/CDV.h (for me I put it in another Bridging-Header.h file within watchkit extension directory, then change the build settings to compile it)

**Comment by alvaroziqar** [comment]
Hi @jingkecn . I follow your step to include MMWormhole in Watch Extension. But I'm having the error "No such module 'MMWormhole" when I try to import it into IntefaceController.swift

I do import of MMWormhole.h in Bridging-Header.h not in other file within watchkit extension.

Do you have any suggestions on what I am doing wrong?

Thanks!!

**Comment by lmuller14** [comment]
Hi @alvaroziqar 

the following steps could help solving your issue:

- Create new `path-to-project/watch Extension/Bridging-Header.h` with the following content

```
#ifndef Bridging_Header_h
#define Bridging_Header_h

#import "MMWormhole.h"
#import "MMWormholeSession.h"

#endif /* Bridging_Header_h */
```
- In Xcode go to watch Extension Build Settings > find “Objective-C Bridging Header”
- Set the value to `$(PROJECT_DIR)/watch Extension/Bridging-Header.h`
- Go to watch Extension Build Phases > find “Compile Sources”
- Click `+` and add all source files with prefix “MMW”

**Comment by alvaroziqar** [comment]
Hi @lmuller14.

Thanks for your answer. I follow this steps but I continue with the same error "No such module 'MMWormhole'". 

I try to import MMWormhole in my InterfaceController.swift as follows:

//
//  InterfaceController.swift
//  MyAPP Extension Extension
//
//  Created by alvaro on 9/10/17.
//

import WatchKit
import Foundation
import MMWormhole

class InterfaceController: WKInterfaceController {

    override func awake(withContext context: Any?) {
        super.awake(withContext: context)
        
        // Configure interface objects here.
    }
    
    override func willActivate() {
        // This method is called when watch view controller is about to be visible to user
        super.willActivate()
        
        let watchConnectivityListeningWormhole = MMWormholeSession.sharedListeningSession();
        watchConnectivityListeningWormhole.activateSessionListening();
        
        let wormhole = MMWormhole(applicationGroupIdentifier: "group.com.yourcompany", optionalDirectory: nil, transitingType: .SessionContext);
    }
    
    override func didDeactivate() {
        // This method is called when watch view controller is no longer visible
        super.didDeactivate()
    }

}


Is this the right way?

Thanks again!

**Comment by lmuller14** [comment]
@alvaroziqar can you try commenting out the `import MMWormhole` or just remove the import?

**Comment by alvaroziqar** [comment]
thanks @lmuller14! it works!!
