### ISSUE TITLE
Not able to add in existing Project

### ISSUE THREAD

**Issue by ashvin777** [leecrossley/cordova-plugin-apple-watch#53]
While I am trying add this plugin in the my existing project I am getting below error. I have tried platform add and remove as well but same result. Also tried to change the deployment target in Xcode to 8.2 and higher but still seeing the same thing.

```
bash-3.2# cordova plugin add cordova-plugin-apple-watch
Installing "cordova-plugin-apple-watch" for ios
Plugin doesn't support this project's apple-ios version. apple-ios: 8.1.0, failed version requirement: >=8.2.0
Skipping 'cordova-plugin-apple-watch' for ios
```

**Comment by leecrossley** [comment]
you need to target iOS >=8.2 to be able to install the plugin
