### ISSUE TITLE
applewatch is not defined

### ISSUE THREAD

**Issue by sagargajera** [leecrossley/cordova-plugin-apple-watch#58]
For IOS:
Though I have installed applewatch plugin and it will be placed in project structure appropriately. I got error like - "can't find variable:applewatch" . 
I also tried to remove plugin and add it again, Checked plugin.xml as well. Nothing helps me.
If anyone has solution for these, please help me,

**Comment by JasonTolliver** [comment]
@sagargajera your error seems strange to me...  If you called `applewatch` from pure JS you should be getting something more like `Uncaught ReferenceError: applewatch is not defined`, so I don't think we're seeing the full story here...

Anyhow, hope you figured it out, but if not I would look into your `cordova` setup and why your plugins aren't available.  Or feel free to share more deets 😉

**Comment by sagargajera** [comment]
Thank you @JasonTolliver . I have found another way to solve it out. Actually I have backboneJS structure with requirJS. So cordova.js may be overrridden there.
