### ISSUE TITLE
cordova plug in

### ISSUE THREAD

**Issue by vivekmayilitta** [leecrossley/cordova-plugin-apple-watch#6]
actually i couldn't init applewatch. applewatch.init is getting an error "Uncaught TypeError: Cannot read property 'applewatch' of undefined" with this problem i couldn't go further.

please help me

**Comment by leecrossley** [comment]
This generally means the plugin is not installed correctly. Please install using:

```
cordova plugin add https://github.com/leecrossley/cordova-plugin-apple-watch.git
```

If the problem persists please recreate the platform and check your filesystem permissions. This is not an issue with the actual plugin.
