### ISSUE TITLE
Can't send a message from WatchKit Extension

### ISSUE THREAD

**Issue by JasonTolliver** [leecrossley/cordova-plugin-apple-watch#60]
Environment:
- **Plugin Version:** 0.11.5
- **Xcode Version:** Xcode 8.1 (8B62)
- **iOS Version:** 10.1

When attempting to use the recommended code for sending a message from watchOS to iOS, I am confronted with the following error in Xcode: `Cannot convert value of type 'String' to expected argument type 'NSCoding?'`

Example code:
```
wormhole.passMessageObject("titleString", identifier: "from_watch_queue")
```

![screen shot 2016-12-02 at 5 10 20 pm](https://cloud.githubusercontent.com/assets/346273/20855519/b5936c38-b8b2-11e6-9c38-b988b7a4c3c3.png)

**Comment by lmuller14** [comment]
The following code should work:
`wormhole.passMessageObject("titleString" as NSCoding?, identifier: "from_watch_queue");`

**Comment by JasonTolliver** [comment]
@lmuller14 thanks that worked like a charm!
