### ISSUE TITLE
Does it actually work? 

### ISSUE THREAD

**Issue by ragcsalo** [leecrossley/cordova-plugin-apple-watch#65]
Hi guys,
Does this plugin still work with the latest batch of Apple Watches? It's weird that I couldn't find any working example for Apple Watch support for Cordova... I guess many developers would like to add watch support to their apps. Any help would be appreciated! 😊

**Comment by ragcsalo** [comment]
Anyone still maintaining this plugin, or is it dead? Are there any other plugins that actually work? 🤔

**Comment by nickredding** [comment]
Try https://github.com/nickredding/cordova-plugin-apple-watch-link

A new plugin that works. I don't think this one works since it's been years since it has been updated.

**Comment by ragcsalo** [comment]
Thanks :-)
In the meantime I've found a working version here: https://github.com/guikeller/cordova-watchconnectivity-plugin
And I've managed to send and receive data from/to my cordova app. :-)
