### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by schnti** [leecrossley/cordova-plugin-apple-watch#9]
Very nice Plugin. Is there any tutorial?

**Comment by JoergHolz** [comment]
+1

**Comment by mattrayner** [comment]
+1

**Comment by leecrossley** [comment]
The readme has been updated with more information to help you understand the different types of communication. There are now also [message passing examples](https://github.com/leecrossley/cordova-plugin-apple-watch#message-passing-examples) to get you started.

If you have specific issues, please open an individual issue. Thanks.

**Comment by JoergHolz** [comment]
Thank's, that helps a lot.

**Comment by hirbod** [comment]
I'm experienced with cordova and creating hybrid app's, and do some manipulation on obj-c, but I really would love to see a example (and usable) default watch app or a tutorial how to create it. I watched a lot of videos today, but they are not so helpful.

How can I start? Basically, I only need to send custom messages to the watch. Nothing special. Just like forwarding notifications (not push, as this works out of the box), but own messages. Do you have any guide here for me? Would also post a bounty for that.
